version: "3"

services:
  backend:
    build: ./
    ports:
      - "8000:8000"
    expose:
      - "8000"
    depends_on:
      - database
  database:
    image: postgres:14.1-alpine
    environment:
      POSTGRES_PASSWORD: "admin"
    ports:
      - "5432:5432"
    expose:
      - "5432"
networks:
  default:
    driver: bridge